# Generated by Django 3.2.8 on 2021-11-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('One', '1/5'), ('Two', '2/5'), ('Three', '3/5'), ('Four', '4/5'), ('Five', '5/5')], default='Five', max_length=5),
        ),
    ]
